import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

// 从 aggregate.json 生成 cordis.patch.yml（参考 @linxin666/dsh-web-ui-all 的 aggregate 思路）。
// 用法: node scripts/aggregate.mjs
const root = dirname(dirname(fileURLToPath(import.meta.url)))
const manifest = JSON.parse(readFileSync(join(root, 'aggregate.json'), 'utf8'))

function scalar(v) {
  if (typeof v === 'string') return JSON.stringify(v)
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'boolean' || typeof v === 'number') return String(v)
  throw new Error('unsupported scalar: ' + typeof v)
}

function isPlainObject(v) {
  return v !== null && typeof v === 'object' && !Array.isArray(v)
}

function yamlLines(value, indent) {
  const pad = ' '.repeat(indent)
  if (Array.isArray(value)) {
    const lines = []
    for (const item of value) {
      if (isPlainObject(item)) {
        const entries = Object.entries(item)
        const allScalar = entries.every(([, v]) => v === null || ['string', 'boolean', 'number'].includes(typeof v))
        if (allScalar && entries.length > 0) {
          lines.push(pad + '- ' + entries[0][0] + ': ' + scalar(entries[0][1]))
          for (const [k, v] of entries.slice(1)) lines.push(pad + '  ' + k + ': ' + scalar(v))
        } else {
          lines.push(pad + '-')
          lines.push(yamlLines(item, indent + 2))
        }
      } else {
        lines.push(pad + '- ' + scalar(item))
      }
    }
    return lines.join('\n')
  }
  if (isPlainObject(value)) {
    const lines = []
    for (const [k, v] of Object.entries(value)) {
      if (isPlainObject(v) || Array.isArray(v)) {
        lines.push(pad + k + ':')
        lines.push(yamlLines(v, indent + 2))
      } else {
        lines.push(pad + k + ': ' + scalar(v))
      }
    }
    return lines.join('\n')
  }
  return pad + scalar(value)
}

const out = []
out.push('# AUTO-GENERATED by scripts/aggregate.mjs — do not edit')
out.push('# Source of truth: aggregate.json; rerun `node scripts/aggregate.mjs` after edits.')
out.push('# Row ids are namespaced combo-* so the bundle can coexist with standalone installs.')
out.push('- insert:')
out.push(yamlLines(manifest.rows.map(r => ({ id: r.id, name: r.name })), 2))
for (const row of manifest.rows) {
  if (row.config) {
    out.push('')
    out.push(`- id: ${row.id}`)
    out.push('  config:')
    out.push(yamlLines(row.config, 4))
  }
}
writeFileSync(join(root, 'cordis.patch.yml'), out.join('\n') + '\n', 'utf8')
console.log('cordis.patch.yml regenerated with ' + manifest.rows.length + ' rows')
